name: Auto approve depfu

on:
  pull_request:
    types:
      - opened

jobs:
  approve:
    if: github.actor == 'depfu[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/auto-approve-action@v2.0.0
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'