name: Format Code

on:
  push:
    branches:
      - master

env:
  node_version: 14

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ env.node_version }}
      - run: yarn --frozen-lockfile
        env:
          CI: true
      - run: yarn format
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[ci] yarn format"
          branch: ${{ github.head_ref }}
          push_options: --force
